[build-system]
requires = [
    "setuptools >= 44.1.1",
    "tomli; python_version < '3.11'",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py36', 'py37', 'py38']

[tool.towncrier]
filename = "NEWS.rst"
package_dir = "src/"
package = "incremental"
