[build-system]
requires = [
    "setuptools >= 61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "incremental"
dynamic = ["version"]
maintainers = [
    {name = "Amber Brown", email = "hawkowl@twistedmatrix.com"},
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8"
license = {file = "LICENSE"}
description = "A small library that versions your Python projects."
readme = "README.rst"
dependencies = [
    "setuptools >= 44.1.1",
    "tomli; python_version < '3.11'",
]

[project.optional-dependencies]
scripts = [
    "click>=6.0",
    "twisted>=16.4.0",
]
mypy = [
    "mypy==0.812",
]

[project.urls]
Homepage = "https://github.com/twisted/incremental"
Documentation = "https://twisted.org/incremental/docs/"
Issues = "https://github.com/twisted/incremental/issues"
Changelog = "https://github.com/twisted/incremental/blob/trunk/NEWS.rst"

[project.entry-points."distutils.setup_keywords"]
use_incremental = "incremental:_get_distutils_version"
[project.entry-points."setuptools.finalize_distribution_options"]
incremental = "incremental:_get_setuptools_version"

[tool.setuptools.dynamic]
version = {attr = "incremental._setuptools_version"}

[tool.black]
target-version = ['py36', 'py37', 'py38']

[tool.towncrier]
filename = "NEWS.rst"
package_dir = "src/"
package = "incremental"
issue_format = "`#{issue} <https://github.com/twisted/incremental/issues/{issue}>`__"
