[build-system]
requires = [
    "setuptools >= 44.1.1",
    "wheel >= 0.36.2",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py36', 'py37', 'py38']

[tool.towncrier]
filename = "NEWS.rst"
package_dir = "src/"
package = "incremental"
